export enum ApiPaths {
  Properties = 'properties',
  UnapprovedProperties = 'properties/unapproved',
  MyProperties = 'my-properties',
  ApproveProperty = 'approve',
  Amenities = 'amenities',
  Profile = 'accounts',
  LogIn = 'auth/login',
  LogOut = 'auth/logout',
  Reservations = 'reservations',
  IncomingReservations = 'incoming-reservations',
  AcceptedReservations = 'accepted-reservations',
  Verification = 'accounts/verify',
  Reviews = 'reviews',
}
