enum NotificationType {
  PROPERTY_REVIEW = "PROPERTY_REVIEW",
  HOST_REVIEW = "HOST_REVIEW",
  RESERVATION_CREATED = "RESERVATION_CREATED",
  RESERVATION_CANCELED = "RESERVATION_CANCELED",
  RESERVATION_ACCEPTED = "RESERVATION_ACCEPTED",
  RESERVATION_REJECTED = "RESERVATION_REJECTED"
}

export default NotificationType;
